site_name: Mentoring-Handbuch
strict: true

theme:
  name: material
  language: de
  logo: assets/raise-logo-nav.svg
  favicon: assets/favicon-32.png
  palette:
    primary: white

  font:
    text: Lato

  features:
    - navigation.instant
    - navigation.indexes
    - search.highlight
    - search.share

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      base_path: 
        - docs
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - git-revision-date
  - search
  - tags:
      tags_file: tags.md

nav:
  - Home: "index.md"
  - Vision:
    - vision/index.md
  - Journey:
    - journey/index.md
  - Haltung:
    - haltung/index.md
  - Prozess:
    - prozess/index.md
  - Themen:
    - themen/index.md
    - themen/abgrenzung.md
    - "Gefährtenschaft": themen/gefaehrtenschaft.md
    - themen/glaubenssaetze.md
    - themen/gott-hoeren.md
    - "Göttliche Identität": themen/goettliche-identitaet.md
    - themen/mentoring-gespraech.md
  - Tools:
    - ./tools/index.md
    - ./tools/eisenhower-diagramm.md
    - ./tools/erfolge-talente.md
    - ./tools/glaubenssaetze.md
    - "Glory-Runde": ./tools/glory-runde.md
    - ./tools/grow.md
    - ./tools/handfragen.md
    - ./tools/individualitaet.md
    - ./tools/kommunitaet.md
    - ./tools/krisen-lektionen.md
    - ./tools/lebenskurve.md
    - ./tools/leiterschaftserfahrungen.md
    - ./tools/lernziele-definieren.md
    - ./tools/mentoring-fragen.md
    - ./tools/motivationsfaehigkeiten.md
    - ./tools/paradigmen-werte.md
    - ./tools/persoenlichkeitsprofil-liste.md
    - "Potenzial-Dusche": ./tools/potenzial-dusche.md
    - ./tools/potential-einsetzen.md
    - ./tools/pyramide-umstaende.md
    - ./tools/pyramide-werte.md
    - ./tools/segnen.md
  # - Internes:
  #   - changelog.md
  - Tags: "tags.md"
  

