site_name: Mentoring-Handbuch
repo_url: https://github.com/chbndrhnns/raise-mentoring-workbook
strict: false

theme:
  name: material
  language: de
  logo: assets/mobile-menu-logo.svg
  favicon: assets/favicon-32.png
  palette:
    primary: white

  font:
    text: Lato

  features:
    - navigation.instant
    - navigation.indexes
    - search.highlight
    - search.share

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - git-revision-date
  - search

nav:
  - Home: "index.md"
  - Vision:
    - vision/index.md
    - vision/journey.md
  - Haltung:
    - haltung/index.md
  - Prozess:
    - prozess/index.md
  - Themen:
    - themen/index.md
    - themen/mentoring-gespraech.md
  - Tools:
    - ./tools/index.md
    - ./tools/coaching-fragen.md
    - ./tools/lebenskurve.md
    - ./tools/krisen-lektionen.md
    - ./tools/leiterschaftserfahrungen.md
    - ./tools/erfolge-talente.md
    - ./tools/motivationsfaehigkeiten.md
    - ./tools/persoenlichkeitsprofil-liste.md
    - ./tools/paradigmen-werte.md
  - Internes:
    - changelog.md

