site_name: Mentoring-Handbuch
repo_url: https://github.com/chbndrhnns/raise-mentoring-workbook
strict: true

theme:
  name: material
  language: de
  logo: assets/mobile-menu-logo.svg
  favicon: assets/favicon-32.png
  palette:
    primary: white

  font:
    text: Lato

  features:
    - navigation.instant
    - navigation.indexes
    - search.highlight
    - search.share

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - git-revision-date
  - search
  - tags:
      tags_file: tags.md

nav:
  - Home: "index.md"
  - Tags: "tags.md"
  - Vision:
    - vision/index.md
    - vision/journey.md
  - Haltung:
    - haltung/index.md
  - Prozess:
    - prozess/index.md
  - Themen:
    - themen/index.md
    - themen/mentoring-gespraech.md
  - Tools:
    - ./tools/index.md
    - ./tools/coaching-fragen.md
    - ./tools/lebenskurve.md
    - ./tools/krisen-lektionen.md
    - ./tools/leiterschaftserfahrungen.md
    - ./tools/erfolge-talente.md
    - ./tools/motivationsfaehigkeiten.md
    - ./tools/persoenlichkeitsprofil-liste.md
    - ./tools/paradigmen-werte.md
    - ./tools/lernziele-definieren.md
    - ./tools/grow-fragen.md
    - ./tools/eisenhower-diagramm.md
    - ./tools/kommunitaet.md
    - ./tools/individualitaet.md
    - ./tools/potential-einsetzen.md
    - ./tools/pyramiden.md
  - Internes:
    - changelog.md

